FROM    node:4-onbuild
RUN     npm install express
RUN     npm install mysql
RUN     npm install body-parser
RUN     npm install cors
RUN     npm install -g nodemon
RUN     npm install socket.io
RUN     npm install geo-lib --save
EXPOSE 4201