-- MySQL Script generated by MySQL Workbench
-- Sat Oct  1 13:05:01 2016
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema matcha
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `matcha` ;

-- -----------------------------------------------------
-- Schema matcha
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `matcha` DEFAULT CHARACTER SET latin1 ;
USE `matcha` ;

-- -----------------------------------------------------
-- Table `matcha`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `matcha`.`users` ;

CREATE TABLE IF NOT EXISTS `matcha`.`users` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `pseudo` VARCHAR(45) NOT NULL,
  `mail` VARCHAR(45) NOT NULL,
  `password` VARCHAR(200) NOT NULL,
  `salt` VARCHAR(16) NOT NULL,
  `first_name` VARCHAR(45) NOT NULL,
  `last_name` VARCHAR(45) NOT NULL,
  `age` INT(11) NOT NULL DEFAULT '18',
  `sex` ENUM('M', 'F') NOT NULL,
  `orientation` ENUM('M', 'F', 'B') NOT NULL DEFAULT 'B',
  `bio` MEDIUMTEXT NULL DEFAULT NULL,
  `loca_lat` FLOAT(10,6) NULL DEFAULT '0.000000',
  `loca_lng` FLOAT(10,6) NULL DEFAULT '0.000000',
  `score` INT(11) NULL DEFAULT '0',
  `crt_date` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `cookie_key` VARCHAR(45) NULL DEFAULT NULL,
  `mail_verif` VARCHAR(45) NULL DEFAULT NULL,
  `last_connected` VARCHAR(45) NULL DEFAULT 'never',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  UNIQUE INDEX `email_UNIQUE` (`mail` ASC),
  UNIQUE INDEX `pseudo_UNIQUE` (`pseudo` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 66
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `matcha`.`messages`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `matcha`.`messages` ;

CREATE TABLE IF NOT EXISTS `matcha`.`messages` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `content` MEDIUMTEXT NOT NULL,
  `crt_date` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `users_id_from` INT(11) NOT NULL,
  `users_id_to` INT(11) NOT NULL,
  PRIMARY KEY (`id`, `users_id_from`, `users_id_to`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `fk_message_users1_idx` (`users_id_from` ASC),
  INDEX `fk_message_users2_idx` (`users_id_to` ASC),
  CONSTRAINT `fk_message_users1`
    FOREIGN KEY (`users_id_from`)
    REFERENCES `matcha`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_message_users2`
    FOREIGN KEY (`users_id_to`)
    REFERENCES `matcha`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 64
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `matcha`.`notifications`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `matcha`.`notifications` ;

CREATE TABLE IF NOT EXISTS `matcha`.`notifications` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `users_to` INT(11) NOT NULL,
  `users_from` INT(11) NOT NULL,
  `content` MEDIUMTEXT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `notifications_ibfk_1` (`users_to` ASC),
  INDEX `notifications_ibfk_2` (`users_from` ASC),
  CONSTRAINT `notifications_ibfk_1`
    FOREIGN KEY (`users_to`)
    REFERENCES `matcha`.`users` (`id`),
  CONSTRAINT `notifications_ibfk_2`
    FOREIGN KEY (`users_from`)
    REFERENCES `matcha`.`users` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 200
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `matcha`.`pictures`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `matcha`.`pictures` ;

CREATE TABLE IF NOT EXISTS `matcha`.`pictures` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `content` MEDIUMTEXT NOT NULL,
  `main` TINYINT(1) NOT NULL,
  `users_id` INT(11) NOT NULL,
  `crt_date` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`, `users_id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `fk_pictures_users_idx` (`users_id` ASC),
  CONSTRAINT `fk_pictures_users`
    FOREIGN KEY (`users_id`)
    REFERENCES `matcha`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 138
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `matcha`.`relations`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `matcha`.`relations` ;

CREATE TABLE IF NOT EXISTS `matcha`.`relations` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `users_id_from` INT(11) NOT NULL,
  `users_id_to` INT(11) NOT NULL,
  `type` ENUM('L', 'B') NOT NULL,
  `crt_date` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`, `users_id_from`, `users_id_to`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `fk_likes_users1_idx` (`users_id_from` ASC),
  INDEX `fk_likes_users2_idx` (`users_id_to` ASC),
  CONSTRAINT `fk_likes_users1`
    FOREIGN KEY (`users_id_from`)
    REFERENCES `matcha`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_likes_users2`
    FOREIGN KEY (`users_id_to`)
    REFERENCES `matcha`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 245
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `matcha`.`reporteds`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `matcha`.`reporteds` ;

CREATE TABLE IF NOT EXISTS `matcha`.`reporteds` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `users_id_from` INT(11) NOT NULL,
  `users_id_to` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `users_id_from` (`users_id_from` ASC),
  INDEX `users_id_to` (`users_id_to` ASC),
  CONSTRAINT `reporteds_ibfk_1`
    FOREIGN KEY (`users_id_from`)
    REFERENCES `matcha`.`users` (`id`),
  CONSTRAINT `reporteds_ibfk_2`
    FOREIGN KEY (`users_id_to`)
    REFERENCES `matcha`.`users` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `matcha`.`tags`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `matcha`.`tags` ;

CREATE TABLE IF NOT EXISTS `matcha`.`tags` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 84
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `matcha`.`users_has_tags`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `matcha`.`users_has_tags` ;

CREATE TABLE IF NOT EXISTS `matcha`.`users_has_tags` (
  `users_id` INT(11) NOT NULL,
  `tags_id` INT(11) NOT NULL,
  PRIMARY KEY (`users_id`, `tags_id`),
  INDEX `fk_users_has_tags_tags1_idx` (`tags_id` ASC),
  INDEX `fk_users_has_tags_users1_idx` (`users_id` ASC),
  CONSTRAINT `fk_users_has_tags_tags1`
    FOREIGN KEY (`tags_id`)
    REFERENCES `matcha`.`tags` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_users_has_tags_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `matcha`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
